fix: add back rounded_size calculation for moving_plan
NameError: 'rounded_size' is not defined

I removed it when switching to pos_profit but need it for moving_plan!